pub struct ThemeColors {
    pub bg_primary: &'static str,
    pub bg_secondary: &'static str,
    pub bg_tertiary: &'static str,
    pub bg_toolbar: &'static str,
    pub bg_editor: &'static str,
    pub bg_preview: &'static str,
    pub bg_headerbar: &'static str,
    pub text_primary: &'static str,
    pub text_secondary: &'static str,
    pub text_tertiary: &'static str,
    pub accent: &'static str,
    pub accent_hover: &'static str,
    pub border: &'static str,
    pub border_light: &'static str,
    pub shadow: &'static str,
    pub code_bg: &'static str,
    pub selection: &'static str,
    pub link: &'static str,
    pub blockquote_border: &'static str,
    pub blockquote_bg: &'static str,
    pub table_header: &'static str,
    pub table_border: &'static str,
    pub hr_color: &'static str,
    pub scrollbar_track: &'static str,
    pub scrollbar_thumb: &'static str,
}

impl ThemeColors {
    pub fn light() -> Self {
        Self {
            bg_primary: "#F5F5F7",
            bg_secondary: "#FFFFFF",
            bg_tertiary: "#F0F0F2",
            bg_toolbar: "#FAFAFA",
            bg_editor: "#FFFFFF",
            bg_preview: "#FAFAFA",
            bg_headerbar: "linear-gradient(180deg, #F8F8FA 0%, #F0F0F3 100%)",
            text_primary: "#1D1D1F",
            text_secondary: "#6E6E73",
            text_tertiary: "#86868B",
            accent: "#007AFF",
            accent_hover: "#0056CC",
            border: "#D2D2D7",
            border_light: "#E5E5EA",
            shadow: "rgba(0, 0, 0, 0.08)",
            code_bg: "#F5F5F7",
            selection: "#007AFF33",
            link: "#007AFF",
            blockquote_border: "#D2D2D7",
            blockquote_bg: "#F5F5F7",
            table_header: "#F5F5F7",
            table_border: "#D2D2D7",
            hr_color: "#D2D2D7",
            scrollbar_track: "transparent",
            scrollbar_thumb: "#C7C7CC",
        }
    }

    pub fn dark() -> Self {
        Self {
            bg_primary: "#1C1C1E",
            bg_secondary: "#2C2C2E",
            bg_tertiary: "#38383A",
            bg_toolbar: "#242426",
            bg_editor: "#1C1C1E",
            bg_preview: "#242426",
            bg_headerbar: "linear-gradient(180deg, #2C2C2E 0%, #1C1C1E 100%)",
            text_primary: "#F5F5F7",
            text_secondary: "#98989D",
            text_tertiary: "#636366",
            accent: "#0A84FF",
            accent_hover: "#409CFF",
            border: "#38383A",
            border_light: "#48484A",
            shadow: "rgba(0, 0, 0, 0.3)",
            code_bg: "#2C2C2E",
            selection: "#0A84FF33",
            link: "#0A84FF",
            blockquote_border: "#48484A",
            blockquote_bg: "#2C2C2E",
            table_header: "#2C2C2E",
            table_border: "#38383A",
            hr_color: "#38383A",
            scrollbar_track: "transparent",
            scrollbar_thumb: "#48484A",
        }
    }

    pub fn sepia() -> Self {
        Self {
            bg_primary: "#F4ECD8",
            bg_secondary: "#FAF4E8",
            bg_tertiary: "#EDE0C8",
            bg_toolbar: "#F0E6D0",
            bg_editor: "#FAF4E8",
            bg_preview: "#F4ECD8",
            bg_headerbar: "linear-gradient(180deg, #F0E6D0 0%, #E8DCC4 100%)",
            text_primary: "#5C3D2E",
            text_secondary: "#8B6914",
            text_tertiary: "#A08060",
            accent: "#A65D2C",
            accent_hover: "#8B4E22",
            border: "#D4C5A9",
            border_light: "#DDD0BA",
            shadow: "rgba(92, 61, 46, 0.1)",
            code_bg: "#EDE0C8",
            selection: "#A65D2C33",
            link: "#8B5E3C",
            blockquote_border: "#D4C5A9",
            blockquote_bg: "#EDE0C8",
            table_header: "#EDE0C8",
            table_border: "#D4C5A9",
            hr_color: "#D4C5A9",
            scrollbar_track: "transparent",
            scrollbar_thumb: "#C4B49A",
        }
    }
}
